### ISSUE TITLE
Diseño del modelo de datos para nuevo resoluciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_crud#25]
Según el [análisis](https://github.com/udistrital/resoluciones_cliente/issues/99) realizado sobre el nuevo resoluciones, así como las [historias de usuario](https://github.com/udistrital/resoluciones_cliente/issues/94) creadas y las recomendaciones realizadas por en Ingeniero Andres, diseñar el modelo de datos desde cero para el nuevo resoluciones.

**Criterios de aceptación**

- [x] Diseño del modelo de datos para su validación.

**Comment by jupmorenor** [comment]
Se realizó revisión del modelo de datos existente de resoluciones con el fin de evaluar que tan necesario es hacer un modelo desde cero, se considera que este modelo es funcional, entonces se le agregan pequeños cambios para soportar nuevas funcionalidades.
![resoluciones v2](https://user-images.githubusercontent.com/11802554/137491794-d27fbf20-73f5-47ac-a811-05c46c72c9e1.png)

**Comment by a52290451** [comment]
Sujeto a validación por parte de DBAs, Arquitectura y Soporte

**Comment by a52290451** [comment]
Se etiqueta a @abriuh para brindar su punto de vista acerca del modelo.

**Comment by jupmorenor** [comment]
Se realizan modificaciones al modelo de datos de acuerdo a las observaciones hechas durante la reunión de validación, especialmente el retiro de las tablas paramétricas para mover esos registros al esquema parámetros y se agrega la documentación correspondiente dentro del modelo, también se cambiaron tipos de datos donde era character varying muy grande por tipo text por conveniencia:

![resoluciones_new](https://user-images.githubusercontent.com/11802554/139070967-628afba5-8d4c-43da-a615-0ab78c05bfab.png)

**Comment by jupmorenor** [comment]
Durante la segunda revisión del modelo de datos trabajado se sugirió agregar una tabla para almacenar los datos correspondientes a los rubros presupuestales de cada vinculación, se hizo una revisión del subsistema de presupuesto con el apoyo del equipo de Kronos para comprender cuales son los datos que debe almacenar esta tabla y así mismo identificar los servicios a utilizar por parte del nuevo Resoluciones. Esto es consecuencia de que las apis financieras anteriores se encuentran deprecadas.

![resoluciones_new](https://user-images.githubusercontent.com/11802554/141152862-35a39214-378b-4453-b1d0-1d1c69908e53.png)
